spring:
  application:
    name: goods
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      percentage: 1
server:
  port: 8070

motan:
  annotaiong-package: moe.cnkirito.sleuth.goods
  client-group: cnkirito
  client-access-log: true
  server-group: cnkirito
  server-access-log: true
  export-port: ${random.int[9001,9999]}
  zookeeper-host: localhost:2181